services:
  redis:
    image: redis/redis-stack:latest
    volumes:
      - ./data:/data
    ports:
      - '6379:6379'
      - '8001:8001'
    restart: always

  app:
    build: ./app
    volumes:
      - ./app:/usr/src/app
    ports:
      - '8080:8080'
      - '80:80'
    env_file:
      - .env
    restart: always
    # depends_on:
    #   - redis
